[build]
  publish = "dist"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "18"

[[edge_functions]]
  function = "subscribe-mailchimp"
  path = "/api/subscribe-mailchimp"


[[edge_functions]]
  function = "contact-slack"
  path = "/api/contact-slack"

[[edge_functions]]
  function = "contact-mailgun"
  path = "/api/contact-mailgun"

[[edge_functions]]
  function = "contact-postmark"
  path = "/api/contact-postmark"


